/*global define*/
define({
    ACTORS_LABEL : '主演：',
    ALIAS_LABEL : '别名：',
    ALL : '全部',
    APP_INSTALL : '安装',
    AREAS : '产地',
    BIRTH_AT : '出生于',
    CATEGORY : '类型',
    CHANNEL : '频道',
    COMIC : '动漫',
    COMMENT : '评论',
    COMMA : '，',
    DIRECTORS_LABEL : '导演：',
    DOWNLOAD : '离线缓存',
    DOWNLOAD_ALL : '全部离线缓存',
    DOWNLOADCOUNT_LABEL : '离线缓存次数：',
    DUBBINGS_LABEL : '配音：',
    EARLY : '更早',
    EPISODE_DOWNLOAD : '离线缓存',
    EPISODE_NUM : '第 {1} 集',
    EPISODE_NUM_SHORTEN : '第{1}集',
    EPISODE_NUM_VARIETY : '第{1}期',
    EXTRA_INFO : '其它信息',
    FROM : '来自',
    HOT : '热门',
    INDEX : '首页',
    INTERNET : '互联网',
    LANGUAGE_LABEL : '语言：',
    LOAD_MORE : '显示更多',
    LOADING : '请稍候...',
    GENDER : ['男', '女'],
    MORE : '更多',
    MOVIE : '电影',
    NO_DATA : '暂无数据',
    NO_RATING : '暂无评分',
    PLAY : '在线播放',
    PRESENTER_LABEL : '主持人：',
    PROVIDERNAMES_LABEL : '来源：',
    RATING : '评分',
    RATING_LABEL : '评分：',
    REGION : '地区',
    REGION_LABEL : '地区：',
    REL : '相关度',
    SCREENWRITERS_LABEL : '编剧：',
    SORT : '排序',
    SOURCE_FROM: '来自',
    STILLS : '剧照',
    STILLS_COUNT : '{1} 张',
    SUBSCRIBE : '手机追追看',
    SUBSCRIBING : '正在追',
    TASK_BEGIN : '任务已开始',
    TIME : '年代',
    TV : '电视剧',
    UNSUBSCRIBE : '不追了',
    UPDATE_TIME : '更新时间',
    VARIETY : '综艺',
    VIDEO_WORKS : '影视作品',
    VIEW : '查看',
    YEAR : '{1} 年'
});
