/*global define*/
define({
    ACTORS_LABEL : '主演：',
    ALIAS_LABEL : '别名：',
    ALL : '全部',
    APP_INSTALL : '安装',
    AREAS : '产地',
    CATEGORY : '类型',
    CHANNEL : '频道',
    COLLAPSE : '收起',
    COMIC : '动漫',
    COMMENTS : '评论',
    DETAIL : '详情',
    DIRECTORS_LABEL : '导演：',
    DOWNLOAD : '缓存',
    DOWNLOAD_ALL : '全部缓存',
    DOWNLOADCOUNT_LABEL : '离线缓存次数：',
    DUBBINGS_LABEL : '配音：',
    DURATION : '片长',
    EARLY : '更早',
    EPISODE_DOWNLOAD : '离线缓存',
    EPISODE_NUM : '第 {1} 集',
    EPISODE_NUM_SHORTEN : '第{1}集',
    EPISODE_NUM_VARIETY : '第{1}期',
    EXTRA_INFO : '其它信息',
    HOT : '热门',
    INDEX : '首页',
    INTERNET : '互联网',
    LANGUAGE_LABEL : '语言：',
    LAST_EPISODE : '更新至 {0} 集',
    LOAD_MORE : '显示更多',
    LOADING : '请稍候...',
    MINUTES : '分钟',
    MORE : '更多',
    MOVIE : '电影',
    NO_DATA : '暂无数据',
    NO_RATING : '暂无评分',
    OTHER_INFO : '其它信息',
    OTHER_NAMES : '又名',
    PERSON : '影人',
    PLAY : '播放',
    PLAYBUTTON_ALT : '点击播放',
    PRESENTER_LABEL : '主持人：',
    PROVIDERNAMES_LABEL : '来源：',
    RATING : '评分',
    RATING_LABEL : '评分：',
    REGION : '地区',
    REGION_LABEL : '地区：',
    REL : '相关度',
    RELATED : '相关',
    RELATED_SERIES : '系列',
    RELATED_VIDEO : '其他人也看了',
    RELEASE_DATE : '上映',
    SCREENWRITERS_LABEL : '编剧：',
    SERIES : '剧集',
    SORT : '排序',
    SOURCE_FROM: '来自',
    STILLS : '剧照',
    STILLS_COUNT : '{1} 张',
    SUBSCRIBE : '追我',
    SUBSCRIBING : '正在追',
    TAB_EARLIEST : '最早',
    TAB_NEWEST : '最新',
    TASK_BEGIN : '任务已开始',
    TIME : '年代',
    TOTLE_COMPLATE : '{0} 集全',
    TRAILOR : '预告片',
    TV : '电视剧',
    UNSUBSCRIBE : '不追了',
    UPDATE_EPISODE : '第 {1} 集',
    UPDATE_TIME : '更新时间',
    VARIETY : '综艺',
    VIDEO : '视频',
    VIDEO_WORKS : '影视作品',
    VIDEO_WORKS_WITH_NUMBER : ' 部影视作品',
    VIEW : '查看',
    YEAR : '{1} 年'
});
