/*global define*/
define({
    ACTORS_LABEL : '主演：',
    PRESENTER_LABEL : '主持人：',
    RATING_LABEL : '评分：',
    YEAR : '{1} 年',
    DOWNLOAD : '下载',
    DOWNLOAD_ALL : '下载全部',
    SUBSCRIBE : '手机追追看',
    SUBSCRIBING : '正在追',
    UNSUBSCRIBE : '不追了',
    COMMENT : '评论',
    LOAD_MORE : '显示更多',
    EXTRA_INFO : '其他信息',
    AREAS : '产地',
    CATEGORY : '类型',
    TIME : '年代',
    ALL : '全部',
    TV : '电视剧',
    MOVIE : '电影',
    COMIC : '动漫',
    VARIETY : '综艺',
    NO_DATA : '暂无数据',
    NO_RATING : '暂无评分',
    EPISODE_DOWNLOAD : '分集下载',
    EPISODE_NUM : '第 {1} 集',
    ALIAS_LABEL : '别名：',
    SCREENWRITERS_LABEL : '编剧：',
    DIRECTORS_LABEL : '导演：',
    DUBBINGS_LABEL : '配音：',
    LANGUAGE_LABEL : '语言：',
    REGION_LABEL : '地区：',
    DOWNLOADCOUNT_LABEL : '下载次数：',
    REGION : '地区',
    EARLY : '更早',
    SORT : '排序',
    HOT : '热门',
    RATING : '评分',
    UPDATE_TIME : '更新时间',
    CHANNEL : '频道',
    REL : '相关度',
    STILLS : '剧照',
    STILLS_COUNT : '{1} 张',
    PROVIDERNAMES_LABEL : '来源：',
    INTERNET : '互联网'
});
